### ISSUE TITLE
CT cannot read properties of undefined

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/number-play#74] opened 2021-11-23 17:28 UTC
```
number-play : fuzz : built
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1637662989114/number-play/build/phet/number-play_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22number-play%22%2C%22fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1637662989114%22%2C%22timestamp%22%3A1637674628908%7D&fuzz&memoryLimit=1000
Query: fuzz&memoryLimit=1000
Uncaught TypeError: Cannot read properties of undefined (reading 'x')
TypeError: Cannot read properties of undefined (reading 'x')
at hi.distanceSquared (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1637662989114/number-play/build/phet/number-play_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22number-play%22%2C%22fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1637662989114%22%2C%22timestamp%22%3A1637674628908%7D&fuzz&memoryLimit=1000:868:114701)
at hi.distance (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1637662989114/number-play/build/phet/number-play_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22number-play%22%2C%22fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1637662989114%22%2C%22timestamp%22%3A1637674628908%7D&fuzz&memoryLimit=1000:868:114579)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1637662989114/number-play/build/phet/number-play_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22number-play%22%2C%22fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1637662989114%22%2C%22timestamp%22%3A1637674628908%7D&fuzz&memoryLimit=1000:868:1672611
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1637662989114/number-play/build/phet/number-play_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22number-play%22%2C%22fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1637662989114%22%2C%22timestamp%22%3A1637674628908%7D&fuzz&memoryLimit=1000:855:22645
at vt (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1637662989114/number-play/build/phet/number-play_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22number-play%22%2C%22fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1637662989114%22%2C%22timestamp%22%3A1637674628908%7D&fuzz&memoryLimit=1000:855:5375)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1637662989114/number-play/build/phet/number-play_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22number-play%22%2C%22fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1637662989114%22%2C%22timestamp%22%3A1637674628908%7D&fuzz&memoryLimit=1000:855:22620
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1637662989114/number-play/build/phet/number-play_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22number-play%22%2C%22fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1637662989114%22%2C%22timestamp%22%3A1637674628908%7D&fuzz&memoryLimit=1000:855:21586
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1637662989114/number-play/build/phet/number-play_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22number-play%22%2C%22fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1637662989114%22%2C%22timestamp%22%3A1637674628908%7D&fuzz&memoryLimit=1000:855:28028
at Ee (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1637662989114/number-play/build/phet/number-play_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22number-play%22%2C%22fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1637662989114%22%2C%22timestamp%22%3A1637674628908%7D&fuzz&memoryLimit=1000:855:21557)
at Ue (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1637662989114/number-play/build/phet/number-play_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22number-play%22%2C%22fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1637662989114%22%2C%22timestamp%22%3A1637674628908%7D&fuzz&memoryLimit=1000:855:22582)
id: Bayes Chrome
Snapshot from 11/23/2021, 3:23:09 AM

----------------------------------

number-play : multitouch-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1637662989114/number-play/number-play_en.html?continuousTest=%7B%22test%22%3A%5B%22number-play%22%2C%22multitouch-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1637662989114%22%2C%22timestamp%22%3A1637674208434%7D&brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=false
Query: brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=false
Uncaught TypeError: Cannot read properties of undefined (reading 'x')
TypeError: Cannot read properties of undefined (reading 'x')
at Vector2.distanceSquared (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1637662989114/chipper/dist/dot/js/Vector2.js:84:35)
at Vector2.distance (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1637662989114/chipper/dist/dot/js/Vector2.js:61:31)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1637662989114/chipper/dist/number-play/js/common/model/OnesPlayArea.js:234:54
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1637662989114/sherpa/lib/lodash-4.17.4.js:3738:18
at arrayMap (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1637662989114/sherpa/lib/lodash-4.17.4.js:660:23)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1637662989114/sherpa/lib/lodash-4.17.4.js:3737:24
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1637662989114/sherpa/lib/lodash-4.17.4.js:3554:27
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1637662989114/sherpa/lib/lodash-4.17.4.js:4920:15
at baseMap (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1637662989114/sherpa/lib/lodash-4.17.4.js:3553:7)
at baseOrderBy (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1637662989114/sherpa/lib/lodash-4.17.4.js:3736:20)
id: Bayes Chrome
Snapshot from 11/23/2021, 3:23:09 AM

----------------------------------

number-play : pan-and-zoom-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1637662989114/number-play/number-play_en.html?continuousTest=%7B%22test%22%3A%5B%22number-play%22%2C%22pan-and-zoom-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1637662989114%22%2C%22timestamp%22%3A1637665151189%7D&brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=true
Query: brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=true
Uncaught TypeError: Cannot read properties of undefined (reading 'x')
TypeError: Cannot read properties of undefined (reading 'x')
at Vector2.distanceSquared (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1637662989114/chipper/dist/dot/js/Vector2.js:84:35)
at Vector2.distance (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1637662989114/chipper/dist/dot/js/Vector2.js:61:31)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1637662989114/chipper/dist/number-play/js/common/model/OnesPlayArea.js:234:54
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1637662989114/sherpa/lib/lodash-4.17.4.js:3738:18
at arrayMap (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1637662989114/sherpa/lib/lodash-4.17.4.js:660:23)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1637662989114/sherpa/lib/lodash-4.17.4.js:3737:24
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1637662989114/sherpa/lib/lodash-4.17.4.js:3554:27
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1637662989114/sherpa/lib/lodash-4.17.4.js:4920:15
at baseMap (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1637662989114/sherpa/lib/lodash-4.17.4.js:3553:7)
at baseOrderBy (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1637662989114/sherpa/lib/lodash-4.17.4.js:3736:20)
id: Bayes Chrome
Snapshot from 11/23/2021, 3:23:09 AM
```

**Comment by pixelzoom** [comment] 2023-01-04 03:51
I did a local build and ran:
http://localhost:8080/number-play/build/phet/number-play_en_phet.html?fuzz&memoryLimit=1000

I could not reproduce this error, and this issue is > 1 year old.  So it was likely fixed. Closing.

**Closed by pixelzoom** 2023-01-04 03:51 UTC
Labels: type:automated-testing
