### ISSUE TITLE
Mandarin voice available for Mongolian locale on chromebook

### ISSUE THREAD

**Issue by stemilymill** [phetsims/number-play#230] opened 2023-04-11 15:56 UTC
For https://github.com/phetsims/qa/issues/929

Device: Lenovo 100e Chromebook 2nd Gen
ChromeOS 112.0.5615.62 (32-bit)

A Mandarin voice is available for Mongolian

** eta: Hakka Chinese is available for Hausa

![mandarin voice for mongolian](https://user-images.githubusercontent.com/85511101/231218562-eb5df882-5fad-42be-bc58-857945520cfe.png)

But no voice is available for any Chinese locale

![but no voice for mandarin](https://user-images.githubusercontent.com/85511101/231218704-fd81930d-9e38-4ebd-9395-aceebc079505.png)

As a side effect, with Mongolian set as locale, the speech synthesis spells out the word by saying "cyrillic" and then the letter name

https://user-images.githubusercontent.com/85511101/231220030-0c62c2ad-ba17-4e85-8645-f0227dc79422.mp4

**Comment by zepumph** [comment] 2023-04-11 21:22
Ok. So we have solved two problems, which were independent and both feel great to fix.

the locale that the voice provides is in a different ISO schema than our supported 

1. A voice.lang like `cmn` (Chinese) was mapping to `mn` (Mongolian) because we were using `.includes`, which was too graceful, instead after https://github.com/phetsims/utterance-queue/commit/8344aa95622303849c9d4b6a213f20d4f78e9c35 we use exact matches for things like `zh_CN`, `zh`, and `zh-CN`
2. Since we don't have any way of supporting these 3 letter codes, we created a map to bring them back to our standard, we only found 3 that were occurring, so it was easy enough to create it manually. 


@stemilymill will you please test this dev version on chromebook to confirm the immediate fix, and on one or two other devices to make sure things seem ok with you. Then we can proceed with cherry picking. Thanks!

Please note that I didn't proceed with the console log to communicate about any other three letter voice.lang values. So no need to check in on that.

https://phet-dev.colorado.edu/html/number-play/1.2.0-dev.1/phet/number-play_all_phet.html

**Comment by stemilymill** [comment] 2023-04-12 20:25
@chrisklus @zepumph 
The original problem looks fixed! Hausa and Mongolian do not have incorrect voices available on chromebook. However...

Firstly, I did a little research and Hakka should definitely not be mapped to `zh` or `zh_CN`, and also probably not `zh_TW` which I think refers to Hokkien and would have the 3-letter code `nam` rather than `hak`.  

Secondly, on my chromebook, the Hakka voice and Cantonese voice do not work at all. The Hakka eSpeak voice says "1, 2, 3" as expected but then while using the sim says "chinese letter" for any number (There is no hakka translation so the hakka voice can just be removed). The Cantonese eSpeak voice does not say anything when clicked on in the preferences menu and then while using the sim, says "letter" for any number. I think there is is actually a problem with the eSpeak voices themselves, since they do the same thing when I have them try to read sample text in the chromebook TTS voice settings. 

The last concern I have is that although I now have the ChromeOS Cantonese voice installed on my chromebook, it is not available in Number Play. I can uninstall and reinstall TTS voices and see them disappear and reappear accordingly in the sim, but not Cantonese. I don't know if this is related to mismatching language codes but they would be `yue` and `zh_HK`

Everything looks fine on my Windows device, and I borrowed another chromebook for a double-check which I am doing now (will edit here when done)

**Comment by KatieWoe** [comment] 2023-04-12 20:45
Things looked ok to me. I didn't catch what @stemilymill saw, but I may not have been looking in the right place or had some different languages.

**Comment by chrisklus** [comment] 2023-04-12 21:51
Thanks for your great investigation @stemilymill! @zepumph and I removed the Hakka voice mapping. We're going to proceed with cherry-picking that change and the RC spot check for today but would like to zoom with you tomorrow to keep looking at the other cases.

**Comment by zepumph** [comment] 2023-04-12 21:51
Noting that we do have the yue -> zh_HK mapping, https://github.com/phetsims/utterance-queue/blob/e92540811428bc658e633be88bb6d8bf916bc533/js/SpeechSynthesisAnnouncer.ts#L121

**Comment by chrisklus** [comment] 2023-04-12 22:20
Patches applied above

**Comment by zepumph** [comment] 2023-04-13 16:19
@stemilymill, @chrisklus and I worked on sorting out the third piece of https://github.com/phetsims/number-play/issues/230#issuecomment-1505880652. The voice.lang was saying `yue-HK`, where as on the other chrome book (or other voice?) it was just `yue`, so we added that mapping as well. We spoke about trying to generalize this, but I can't really think of how we would, so we will just keep up with the mappings.

@stemilymill, if in the future you find this kind of weirdness, you can us browser console filtering like `speechSynthesis.getVoices().filter( x=>x.lang === 'yue')` or `speechSynthesis.getVoices().filter( x=>x.name.includes( 'Chrome OS' )` to see if the lang of the buggy voice means that we need to update our map somewhere around: https://github.com/phetsims/utterance-queue/blob/master/js/SpeechSynthesisAnnouncer.ts#L115-L125

We will cherry pick https://github.com/phetsims/utterance-queue/commit/412dd8468a0e86bd514af54258ae98fba51debce for number-play, but probably not much more unless it is really buggy. 

@stemilymill confirmed this was fixed in a dev version we just created: https://phet-dev.colorado.edu/html/number-play/1.2.0-dev.2/phet/number-play_all_phet.html.

**Comment by chrisklus** [comment] 2023-04-13 21:07
@zepumph and I confirmed the new mappings are in the source code of https://phet-dev.colorado.edu/html/number-play/1.1.0-rc.3/phet/number-play_all_phet.html, I think we are set to close here!

**Closed by chrisklus** 2023-04-13 21:07 UTC
Labels: status:blocks-sim-publication, type:i18n, status:ready-to-cherry-pick
