### ISSUE TITLE
"Unused string" warnings

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/number-play#203] opened 2023-01-15 17:42 UTC
`grunt build` is reporting many unused strings for number-play, see below. Why? Is there something that needs to be addressed? 

(This does not happen for number-compare.) 

```
% cd number-play
% grunt build --brands=phet
...
Building brand: phet
>> Webpack build complete: 4257ms
>> Unused string: key=screen.lab, value=Lab
>> Unused string: key=zero, value=zero
>> Unused string: key=one, value=one
>> Unused string: key=two, value=two
>> Unused string: key=three, value=three
>> Unused string: key=four, value=four
>> Unused string: key=five, value=five
>> Unused string: key=six, value=six
>> Unused string: key=seven, value=seven
>> Unused string: key=eight, value=eight
>> Unused string: key=nine, value=nine
>> Unused string: key=ten, value=ten
>> Unused string: key=eleven, value=eleven
>> Unused string: key=twelve, value=twelve
>> Unused string: key=thirteen, value=thirteen
>> Unused string: key=fourteen, value=fourteen
>> Unused string: key=fifteen, value=fifteen
>> Unused string: key=sixteen, value=sixteen
>> Unused string: key=seventeen, value=seventeen
>> Unused string: key=eighteen, value=eighteen
>> Unused string: key=nineteen, value=nineteen
>> Unused string: key=twenty, value=twenty
>> Unused string: key=total, value=Total
>> Unused string: key=objects, value=Objects
>> Unused string: key=gameNameLevelNumberPattern, value={{gameName}}: Level {{levelNumber}}
>> Unused string: key=readAloudDescription, value=Hear the updated total as you interact.
>> Unused string: key=secondLanguage, value=Second Language
>> Unused string: key=secondLanguageDescription, value=Select a second language to support multilingual learning.
>> Unused string: key=showOnes, value=Show Ones
>> Unused string: key=showOnesDescription, value=Include the paper numbers on the Lab screen.
>> Unused string: key=noDeviceFoundDescription, value=There is no voice found on this device for the selected language(s).
>> Unused string: key=yourDeviceMaySupportDescription, value=Your device may support downloading an additional voice for your language.
...
```

**Comment by pixelzoom** [comment] 2023-01-15 17:50
This may be related to https://github.com/phetsims/number-suite-common/#32.

**Comment by chrisklus** [comment] 2023-01-17 19:53
Duplicate of https://github.com/phetsims/number-suite-common/issues/32, closing.

**Closed by chrisklus** 2023-01-17 19:53 UTC
Labels: type:i18n
