### ISSUE TITLE
Tall characters in some locales extend beyond accordion box

### ISSUE THREAD

**Issue by stemilymill** [phetsims/number-play#222] opened 2023-04-07 16:27 UTC
For https://github.com/phetsims/qa/issues/925
Seen on Win10 and Win11 Chrome, with a couple instances also in Firefox. Not seen on mac.

Certain tall characters extend beyond the accordion box in the Twenty screen when there is a second language in use. Some characters that do technically fit within the box have odd rendering.

Extending outside of box:
- Hindi:  5, 9, 14
- Gujarati: 14

Oddness:
Parts of the characters that are too tall usually do not fully load until mouse is moved, then when going to another number that part stays visible until mouse is moved
- Bengali: 2, 18
- Gujarati: 1, 2, 13, 14, 16
- Hindi: 2, 5, 9, 13, 14, 16

Even though the text does not appear to be close to the edges of the accordion box in the Ten screen, the oddness still occurs there.

**I should note: I saw that google translate has issues with some of these being cut off. I added screenshots in case they are at all useful since it seemed kind of similar

**Example of oddness - note cursor movements**

https://user-images.githubusercontent.com/85511101/230640929-01a8779f-c04a-4b17-a3a7-eb91a8864ffa.mp4

.

**another example of text beyond box borders**

![text extending past accordion box bounds hindi 5](https://user-images.githubusercontent.com/85511101/230641499-772b25f4-b79f-43f1-aac7-5bc0f95fda99.jpg)

What nineteen in Hindi looks like in google translate:

![Screenshot 2023-04-07 114216](https://user-images.githubusercontent.com/85511101/230642855-2dd4fe2f-de9f-4392-b89a-eed92db6144a.png)

A grainy picture of the top not being cut off:

![not cut off](https://user-images.githubusercontent.com/85511101/230642326-e705e1b3-8565-472e-bbc7-f5cc615899ed.png)

**Comment by chrisklus** [comment] 2023-04-07 16:46
Thanks @stemilymill! I cannot reproduce this on my machine so am going to mark as on hold @zepumph is back on Monday and we can take a look together. On Mac + Chrome, it looks like the whole font is scaled down to fix appropriately.

**Comment by chrisklus** [comment] 2023-04-07 17:02
Tagging https://github.com/phetsims/qa/issues/929

**Comment by zepumph** [comment] 2023-04-10 20:37
@chrisklus and I encountered this problem on windows (chrome and firefox). Using `boundsMethod: 'accurate'` is working well, as seen by this script that we added those hindi words to:

http://localhost:8080/scenery/tests/sandbox.html?script=const%20flags%20%3D%20%7B%0A%20%20approximateSVGBounds%3A%20false%2C%0A%20%20approximateDOMBounds%3A%20false%2C%0A%20%20accurateCanvasBoundsFallback%3A%20false%2C%0A%20%20approximateImprovedDOMBounds%3A%20false%2C%0A%20%20accurateCanvasBounds%3A%20true%2C%0A%20%20approximateHybridBounds%3A%20true%0A%7D%3B%0A%0Aconst%20unicodeTestStrings%20%3D%20%5B%20%22%5Cu0928%5Cu094c%22%2C%20%22%5Cu092a%5Cu093e%5Cu0901%5Cu091a%22%2C%20%22A%22%2C%20%22b%22%2C%20%22m%22%2C%20%22x%22%2C%20%27Q%27%2C%20%22A%5Cn%5C%5Cn%22%2C%20%22A%5Cr%5Cn%5C%5Cr%5C%5Cn%22%2C%20%22A%5Ct%5C%5Ct%22%2C%20%22%5Cu222b%22%2C%20%22%5Cufdfa%22%2C%20%22%5Cu00a7%22%2C%20%22%5Cu00C1%22%2C%20%22%5Cu00FF%22%2C%20%22%5Cu03A9%22%2C%20%22%5Cu0906%22%2C%20%22%5Cu79C1%22%2C%20%22%5Cu9054%22%2C%20%22A%5Cu030a%5Cu0352%5Cu0333%5Cu0325%5Cu0353%5Cu035a%5Cu035e%5Cu035e%22%2C%20%220%5Cu0489%22%2C%20%22%5Cu2588%22%20%5D%3B%0Aconst%20styles%20%3D%20%5B%20%7B%20fontSize%3A%2060%20%7D%2C%20%7B%20fontSize%3A%2060%2C%20fontFamily%3A%20%27serif%27%20%7D%2C%20%7B%20fontSize%3A%2060%2C%20fontFamily%3A%20%27monospace%27%20%7D%2C%20%7B%20fontSize%3A%2060%2C%20fontFamily%3A%20%27cursive%27%20%7D%2C%20%7B%20fontSize%3A%2060%2C%20fontFamily%3A%20%27fantasy%27%20%7D%2C%20%7B%20fontSize%3A%2060%2C%20fontFamily%3A%20%27Georgia%2C%20serif%27%20%7D%2C%20%7B%20fontSize%3A%2060%2C%20fontFamily%3A%20%27%22Palatino%20Linotype%22%2C%20%22Book%20Antiqua%22%2C%20Palatino%2C%20serif%27%20%7D%2C%20%7B%20fontSize%3A%2060%2C%20fontFamily%3A%20%27%22Times%20New%20Roman%22%2C%20Times%2C%20serif%27%20%7D%2C%20%7B%20fontSize%3A%2060%2C%20fontFamily%3A%20%27Arial%2C%20Helvetica%2C%20sans-serif%27%20%7D%2C%20%7B%20fontSize%3A%2060%2C%20fontFamily%3A%20%27%22Arial%20Black%22%2C%20Gadget%2C%20sans-serif%27%20%7D%2C%20%7B%20fontSize%3A%2060%2C%20fontFamily%3A%20%27%22Comic%20Sans%20MS%22%2C%20cursive%2C%20sans-serif%27%20%7D%2C%20%7B%20fontSize%3A%2060%2C%20fontFamily%3A%20%27Impact%2C%20Charcoal%2C%20sans-serif%27%20%7D%2C%20%7B%20fontSize%3A%2060%2C%20fontFamily%3A%20%27%22Lucida%20Sans%20Unicode%22%2C%20%22Lucida%20Grande%22%2C%20sans-serif%27%20%7D%2C%20%7B%20fontSize%3A%2060%2C%20fontFamily%3A%20%27Tahoma%2C%20Geneva%2C%20sans-serif%27%20%7D%2C%20%7B%20fontSize%3A%2060%2C%20fontFamily%3A%20%27%22Trebuchet%20MS%22%2C%20Helvetica%2C%20sans-serif%27%20%7D%2C%20%7B%20fontSize%3A%2060%2C%20fontFamily%3A%20%27Verdana%2C%20Geneva%2C%20sans-serif%27%20%7D%2C%20%7B%20fontSize%3A%2060%2C%20fontFamily%3A%20%27%22Courier%20New%22%2C%20Courier%2C%20monospace%27%20%7D%2C%20%7B%20fontSize%3A%2060%2C%20fontFamily%3A%20%27%22Lucida%20Console%22%2C%20Monaco%2C%20monospace%27%20%7D%2C%20%7B%20fontSize%3A%2060%2C%20fontWeight%3A%20%27900%27%20%7D%2C%20%7B%20fontSize%3A%2060%2C%20fontWeight%3A%20%27900%27%20%7D%2C%20%7B%20fontSize%3A%2060%2C%20fontStretch%3A%20%27ultra-condensed%27%20%7D%2C%20%7B%20fontSize%3A%2060%2C%20fontStretch%3A%20%27ultra-expanded%27%20%7D%2C%20%7B%20fontSize%3A%2060%2C%20fontStyle%3A%20%27italic%27%20%7D%2C%20%7B%20fontSize%3A%2060%2C%20fontStyle%3A%20%27oblique%27%20%7D%2C%20%7B%20fontSize%3A%2060%2C%20fontFamily%3A%20%27serif%27%2C%20textAlign%3A%20%27end%27%20%7D%2C%20%7B%20fontSize%3A%2060%2C%20direction%3A%20%27rtl%27%20%7D%2C%20%7B%20fontSize%3A%2060%2C%20direction%3A%20%27rtl%27%20%7D%20%5D%3B%0A%0Aconst%20getTextDemo%20%3D%20(%20string%2C%20textOptions%2C%20scale%20%3D%201%20)%20%3D%3E%20%7B%0A%20%20const%20text%20%3D%20new%20Text(%20string%2C%20textOptions%20)%3B%0A%20%20%0A%20%20return%20new%20Node(%20%7B%0A%20%20%20%20scale%3A%20scale%2C%0A%20%20%20%20children%3A%20%5B%0A%20%20%20%20%20%20...(%20flags.approximateSVGBounds%20%3F%20%5B%20Rectangle.bounds(%20TextBounds.approximateSVGBounds(%20text._font%2C%20text.renderedText%20)%2C%20%7B%20fill%3A%20%27rgba(0%2C0%2C255%2C0.3)%27%20%7D%20)%20%5D%20%3A%20%5B%5D%20)%2C%0A%20%20%20%20%20%20...(%20flags.approximateDOMBounds%20%3F%20%5B%20Rectangle.bounds(%20TextBounds.approximateDOMBounds(%20text._font%2C%20text.getDOMTextNode()%20)%2C%20%7B%20fill%3A%20%27rgba(255%2C0%2C255%2C0.3)%27%20%7D%20)%20%5D%20%3A%20%5B%5D%20)%2C%0A%20%20%20%20%20%20...(%20flags.accurateCanvasBoundsFallback%20%3F%20%5B%20Rectangle.bounds(%20TextBounds.accurateCanvasBoundsFallback(%20text%20)%2C%20%7B%20fill%3A%20%27rgba(255%2C255%2C0%2C0.3)%27%20%7D%20)%20%5D%20%3A%20%5B%5D%20)%2C%0A%20%20%20%20%20%20...(%20flags.approximateImprovedDOMBounds%20%3F%20%5B%20Rectangle.bounds(%20TextBounds.approximateImprovedDOMBounds(%20text._font%2C%20text.getDOMTextNode()%20)%2C%20%7B%20fill%3A%20%27rgba(0%2C255%2C0%2C0.3)%27%20%7D%20)%20%5D%20%3A%20%5B%5D%20)%2C%0A%20%20%20%20%20%20...(%20flags.approximateHybridBounds%20%3F%20%5B%20Rectangle.bounds(%20TextBounds.approximateHybridBounds(%20text._font%2C%20text.renderedText%20)%2C%20%7B%20fill%3A%20%27rgba(0%2C0%2C255%2C0.3)%27%20%7D%20)%20%5D%20%3A%20%5B%5D%20)%2C%0A%20%20%20%20%20%20...(%20flags.accurateCanvasBounds%20%3F%20%5B%20Rectangle.bounds(%20TextBounds.accurateCanvasBounds(%20text%20)%2C%20%7B%20fill%3A%20%27rgba(255%2C0%2C0%2C0.3)%27%20%7D%20)%20%5D%20%3A%20%5B%5D%20)%2C%0A%20%20%20%20%20%20text%0A%20%20%20%20%5D%0A%20%20%7D%20)%3B%0A%7D%3B%0A%0A%2F%2F%20Allow%20scrolling%0Aif%20(%20display._input%20)%20%7B%0A%20%20display.detachEvents()%3B%0A%7D%0A%0Ascene.addChild(%20new%20VBox(%20%7B%0A%20%20spacing%3A%2010%2C%0A%20%20align%3A%20%27left%27%2C%0A%20%20children%3A%20styles.map(%20style%20%3D%3E%20new%20HBox(%20%7B%0A%20%20%20%20spacing%3A%203%2C%0A%20%20%20%20children%3A%20unicodeTestStrings.map(%20string%20%3D%3E%20getTextDemo(%20string%2C%20style%2C%201%20)%20)%2C%0A%20%20%20%20align%3A%20%27origin%27%0A%20%20%7D%20)%20)%0A%7D%20)%20)%3B%0A


There was just some number-play specific layout that wasn't set up to update when that changed. @chrisklus will commit shortly.

**Comment by chrisklus** [comment] 2023-04-10 22:32
Here is the patch that is fixing this problem:

<details>

```diff
Index: js/common/view/WordAccordionBox.ts
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/js/common/view/WordAccordionBox.ts b/js/common/view/WordAccordionBox.ts
--- a/js/common/view/WordAccordionBox.ts	(revision 4aa3d863a361b9ccceeb0ff5a663cd53f73cab43)
+++ b/js/common/view/WordAccordionBox.ts	(date 1681160893558)
@@ -80,11 +80,12 @@
     // initialize as blank, updated in link below
     const wordText = new Text( wordStringProperty, {
       font: options.font,
+      boundsMethod: 'accurate',
       maxWidth: this.contentBoundsProperty.value.width - options.textOffsetX - TEXT_MARGIN
     } );
     this.contentNode.addChild( wordText );
 
-    this.contentBoundsProperty.link( contentBounds => {
+    Multilink.multilink( [ this.contentBoundsProperty, wordText.boundsProperty ], contentBounds => {
       wordText.left = contentBounds.left + options.textOffsetX;
       wordText.centerY = contentBounds.centerY;
     } );

```

</details>

The reason I didn't commit this is because it we are no longer keeping a relative point in the characters in a constant spot, so they are shifting up and down in order to stay in bounds in the accordion box. This is more noticeable on mac, and I think should be considered a bug since it would look weird to us if it was happening in English. I would like to investigate why this font is rendering so much bigger on Windows than Mac. If we could get them a consistent size, the original issue here would not longer be a problem, and we wouldn't need a workaround like a patch above.

**Comment by chrisklus** [comment] 2023-04-11 15:42
From 4/11 standup with @zepumph and @Nancy-Salpepi:

We think this original issue is blocking but the partial fix got it to a non-blocking state. Anything else from here would be nice to have.

**Comment by zepumph** [comment] 2023-04-11 21:43
This paints a pink rectangle behind the bounds of the Text, which helps us understand the cross-platform differences

<details>

```diff
Subject: [PATCH] Map unsupported voice.lang to
---
Index: js/common/view/WordAccordionBox.ts
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/js/common/view/WordAccordionBox.ts b/js/common/view/WordAccordionBox.ts
--- a/js/common/view/WordAccordionBox.ts	(revision 4e8e025f930f4449141a07e5961025e1af056c53)
+++ b/js/common/view/WordAccordionBox.ts	(date 1681249197312)
@@ -80,13 +80,20 @@
     // initialize as blank, updated in link below
     const wordText = new Text( wordStringProperty, {
       font: options.font,
+      // boundsMethod: 'accurate',
       maxWidth: this.contentBoundsProperty.value.width - options.textOffsetX - TEXT_MARGIN
     } );
+
+    const x = new phet.scenery.Node();
+    this.contentNode.addChild( x );
     this.contentNode.addChild( wordText );
 
-    this.contentBoundsProperty.link( contentBounds => {
+    Multilink.multilink( [ this.contentBoundsProperty, wordText.boundsProperty ], contentBounds => {
       wordText.left = contentBounds.left + options.textOffsetX;
       wordText.centerY = contentBounds.centerY;
+      x.children = [
+        phet.scenery.Rectangle.bounds( wordText.bounds, { fill: 'pink' } )
+      ];
     } );
   }
 

```
</details>

A couple ideas on how to proceed:
1. Leave as is, and text sometimes goes outside of the accordionBox, and on windows has some artifacts around the accordionBox edge.
2. Use our patch above with `boundsMethod: 'accurate'` which makes all locales bounce around, including english
3. We saw a bit of difference updating the layout just on text bounds too (the multilink part of the patch without the boundsMethod change), but not too much different.
4. Investigate a list of locales to change the font size for.
5. Investigate a list of locales to toggle the boundsMethod for.

We would like to talk to @amanda-phet because we are torn, and also @chrisklus and I don't agree on which item above is best.

**Comment by zepumph** [comment] 2023-04-12 17:42
Ok, after discussing with @amanda-phet, this is clearly not a Number Play issue. Hindi is often poorly laid out. Furthermore, the "bouncing" of using accurate bounds was really not great, so as a result we will think about this issue more generally, and decide how to proceed over in https://github.com/phetsims/scenery/issues/1551. Closing as a won't fix.

**Closed** 2023-04-12 17:42 UTC
Labels: type:bug, type:wontfix, type:i18n
