### ISSUE TITLE
CT Cannot fire when already firing

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/number-play#190] opened 2022-11-28 16:28 UTC
```
number-play : multitouch-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1669628102736/number-play/number-play_en.html?continuousTest=%7B%22test%22%3A%5B%22number-play%22%2C%22multitouch-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1669628102736%22%2C%22timestamp%22%3A1669636948574%7D&brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=false
Query: brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=false
Uncaught Error: Assertion failed: Cannot fire when already firing
Error: Assertion failed: Cannot fire when already firing
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1669628102736/assert/js/assert.js:28:13)
at assert (PushButtonModel.ts:177:14)
at fire (PushButtonModel.ts:121:15)
at listener (TinyEmitter.ts:95:8)
at emit (ReadOnlyProperty.ts:311:22)
at _notifyListeners (ReadOnlyProperty.ts:262:13)
at unguardedSet (ReadOnlyProperty.ts:246:11)
at set (Property.ts:65:10)
at set (ButtonModel.ts:187:24)
at listener (TinyEmitter.ts:95:8)
id: Bayes Puppeteer
Snapshot from 11/28/2022, 2:35:02 AM
```

**Comment by pixelzoom** [comment] 2023-01-04 22:31
I cannot reproduce this in master with
http://localhost:8080/number-play/number-play_en.html?brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=false

And I do not see this issue in CT history.

I'm concluding that this is no longer a problem, and might have been a transient problem in common code.   So I'll close this issue, and we can reopen if it reoccurs.

**Closed by pixelzoom** 2023-01-04 22:31 UTC
Labels: type:automated-testing
