### ISSUE TITLE
Jumpy Number Cards out of Carousel on Lab Screen

### ISSUE THREAD

**Issue by veillette** [phetsims/number-play#223] opened 2023-04-07 20:35 UTC
Test device
Dell XPS 15

Operating System
Windows 10

Browser
Chrome

Problem description
While working on https://github.com/phetsims/qa/issues/929, I noticed that while working on the lab screens, the dragging behavior of cards out out the carrousel is somewhat jumpy with a mouse. When attempting to drag a number card, a card appears while you press the card. The location of the card is such that the cursor is beneath the number (nice!). However, once a drag is initiated, the card suddenly moves below the carrousel and the cursor is no longer tied to the position of the card.   

It is worth noting that 
https://phet-dev.colorado.edu/html/number-play/1.1.0-dev.10/phet/number-play_all_phet.html?screens=4
does not exhibit this behavior. 

See below for a video/gif
![JumpyCards](https://user-images.githubusercontent.com/7633344/230674107-b24d6edb-15ce-40ef-9059-4a9b68c5e542.gif)

I think that 1.1.0-rc.1 wants to ensure that on the first drag the number card is guaranteed to end up in the play area. Although it does succeed in that respect, however, it seems a bit disconcerting to have the cards jump around to achieve this goal.

**Comment by chrisklus** [comment] 2023-04-08 04:42
Thanks @veillette! Looks like an accidental use of the symbol cards' bounds Property instead of the number cards' that happened during some cleanup.

Fixed in the above commit, assigning @veillette or @KatieWoe to please confirm on phettest, thanks!

SHA for patching: `24776163b74acb9760d44509c9dbc50f1af1104e`.

**Comment by veillette** [comment] 2023-04-10 15:19
@chrisklus: the change above fixes the problem with the number picker carousel on master. Well done.

However, I should point out that the vertical number operation carousel shows a buggy behavior on master, whereas it is perfectly fine on 1.1.0-rc.1. You cannot return the operations in the carousel on master.

**Comment by chrisklus** [comment] 2023-04-10 17:49
Sorry @veillette! That was very silly of me (again). Should be good to go this time, can you please test on phettest?

**Comment by veillette** [comment] 2023-04-10 18:37
Assigning back to @chrisklus

**Comment by chrisklus** [comment] 2023-04-10 18:53
Thanks @veillette!

**Comment by chrisklus** [comment] 2023-04-10 19:35
@zepumph and I applied the SHAs from this issue to the release branch, 1.1, then confirmed locally. We are ready to leave this for RC spot check testing. This can be closed once confirmed in the RC spot check, thanks!

**Comment by KatieWoe** [comment] 2023-04-13 16:58
This looks fixed to me for the most part, but I did notice that moving the cards around caused a sort of flickering of the numbers on the other cards. Is this related and/or an issue?

https://user-images.githubusercontent.com/41024075/231831017-e4aa4b4c-bc3f-43e0-8f38-5ba366e27c52.mp4

**Comment by Nancy-Salpepi** [comment] 2023-04-13 17:05
I also saw that if I grabbed a card close to the top, it initially goes a bit offscreen and then is a little jumpy when I begin to bring it down. Not sure how big of a deal it is. 

https://user-images.githubusercontent.com/87318828/231833130-4d520459-f847-4795-863e-3a3243078a59.mp4

**Comment by veillette** [comment] 2023-04-13 19:09
I observe the same type of behavior as @Nancy-Salpepi and @KatieWoe . However, I would qualify this as minor in comparison to the issue in 1.1.0-rc.1 where one could not bring the cards back to the carousel.  Personally I would think that the drag behavior is much improved in 1.1.0-rc.2 and we can now bring cards back into the carousel.

**Comment by chrisklus** [comment] 2023-04-13 19:24
Thanks all! I discussed with @amanda-phet. We are not concerned about https://github.com/phetsims/number-play/issues/223#issuecomment-1507296015. I have an idea for making https://github.com/phetsims/number-play/issues/223#issuecomment-1507308544 better and think it is worth 10-20 minutes to try, but not blocking.

**Comment by Nancy-Salpepi** [comment] 2023-04-13 20:36
This looks good to me @chrisklus!

**Comment by chrisklus** [comment] 2023-04-13 21:05
Thanks @Nancy-Salpepi! This is looking great in https://phet-dev.colorado.edu/html/number-play/1.1.0-rc.3/phet/number-play_all_phet.html, I think we are set to close here.

**Closed by chrisklus** 2023-04-13 21:05 UTC
Labels: type:bug, status:blocks-sim-publication, status:ready-for-review
