### ISSUE TITLE
SpeechSynthesisAnnouncer cannot be used before initialized 

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/number-play#204] opened 2023-01-17 14:31 UTC
@marlitas I'm not sure what is happening, but with mac + safari when I try to set the second locale, the sim freezes with this error:
<img width="1078" alt="Screenshot 2023-01-17 at 9 02 17 AM" src="https://user-images.githubusercontent.com/87318828/212919131-a88a95ee-29d9-4056-8c77-5e43edf3ff42.png">

When using mac + chrome, I can add the second locale and didn't notice any speech synthesis bugs.

_Originally posted by @Nancy-Salpepi in https://github.com/phetsims/number-play/issues/152#issuecomment-1385481586_

**Comment by marlitas** [comment] 2023-01-17 17:54
I see this with Windows + firefox as well. Was working on https://github.com/phetsims/number-play/issues/160 and got blocked by this.

**Comment by jessegreenberg** [comment] 2023-01-17 20:53
In Win 10 Firefox  I hit this with `secondLocale=es&locales=en,es` but did NOT see this with `locales=*`.

In Win 10 Chrome I hit I am seeing assertions like this instead related to strings not being availabel in unbuilt version:

<details>

```
load-unbuilt-strings.js:176          GET http://localhost:8080/babel/counting-common/counting-common-strings_es.json 404 (Not Found)
requestJSONFile @ load-unbuilt-strings.js:176
(anonymous) @ load-unbuilt-strings.js:270
(anonymous) @ load-unbuilt-strings.js:267
(anonymous) @ load-unbuilt-strings.js:159
load (async)
requestJSONFile @ load-unbuilt-strings.js:150
(anonymous) @ load-unbuilt-strings.js:265
(anonymous) @ load-unbuilt-strings.js:264
(anonymous) @ load-unbuilt-strings.js:278
load-unbuilt-strings.js:176          GET http://localhost:8080/babel/sun/sun-strings_es.json 404 (Not Found)
requestJSONFile @ load-unbuilt-strings.js:176
(anonymous) @ load-unbuilt-strings.js:270
(anonymous) @ load-unbuilt-strings.js:267
(anonymous) @ load-unbuilt-strings.js:159
load (async)
requestJSONFile @ load-unbuilt-strings.js:150
(anonymous) @ load-unbuilt-strings.js:265
(anonymous) @ load-unbuilt-strings.js:264
(anonymous) @ load-unbuilt-strings.js:278
load-unbuilt-strings.js:176          GET http://localhost:8080/babel/tambo/tambo-strings_es.json 404 (Not Found)
requestJSONFile @ load-unbuilt-strings.js:176
(anonymous) @ load-unbuilt-strings.js:270
(anonymous) @ load-unbuilt-strings.js:267
(anonymous) @ load-unbuilt-strings.js:159
load (async)
requestJSONFile @ load-unbuilt-strings.js:150
(anonymous) @ load-unbuilt-strings.js:265
(anonymous) @ load-unbuilt-strings.js:264
(anonymous) @ load-unbuilt-strings.js:278
load-unbuilt-strings.js:176          GET http://localhost:8080/babel/twixt/twixt-strings_es.json 404 (Not Found)
```

</details>


So maybe this Firefox issue is downstream of the strings not being available? Ill try in a built version.

**Comment by jessegreenberg** [comment] 2023-01-17 21:13
OK, proposing the above commit to fix this. Instead of checking for populated voices we check to wait until the SpeechSynthesisAnnouncer has been initialized.

I am not sure when `updateVoice` needs to be called but if it has to be called on startup, you could also link it to the 
`SpeechSynthesisAnnouncer.isInitializedProperty` as well.

**Comment by jessegreenberg** [comment] 2023-01-17 21:20
> @[jessegreenberg](https://github.com/jessegreenberg) jessegreenberg closed this as [completed](https://github.com/phetsims/number-play/issues?q=is%3Aissue+is%3Aclosed+archived%3Afalse+reason%3Acompleted) in https://github.com/phetsims/number-suite-common/commit/a33e8c017b59390eddf10aea120c0bbd3a65fee1 [1 minute ago](https://github.com/phetsims/number-play/issues/204#event-8249860919)

Sorry, not my intention.

**Comment by pixelzoom** [comment] 2023-01-18 03:39
Over in https://github.com/phetsims/number-suite-common/issues/33, I reported that both number-play and number-compare are currently failing to start in Chrome when run from phetmarks.  This is blocking further development and top priority.  @chrisklus seems to think this issue is the cause.

**Comment by jessegreenberg** [comment] 2023-01-18 14:32
Sorry about that! I guess I did not test https://github.com/phetsims/number-suite-common/commit/3e1652f1f9f388d1253888c4fc5612c60f2b06e9. Fixed with the above commit.

**Comment by marlitas** [comment] 2023-01-18 21:11
@jessegreenberg this looks good, thanks for the work here! @chrisklus over to you for final review and closure.

**Comment by chrisklus** [comment] 2023-01-18 22:30
Reviewed and discussed with @marlitas on Slack, changes look great and I tested on Safari and Chrome. Thanks @marlitas and @jessegreenberg! Closing.

**Closed by chrisklus** 2023-01-18 22:30 UTC
Labels: status:blocks-sim-publication, status:ready-for-review
