### ISSUE TITLE
CT Missing string information

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/number-play#72] opened 2021-11-08 17:22 UTC
```
number-play : build
Build failed with status code 1:
Running "report-media" task

Running "clean" task

Running "build" task
>> TypeScript compilation complete: 112323ms
Building runnable repository (number-play, brands: phet)
Building brand: phet
>> Webpack build complete: 7468ms
>> Unused images module: number-play/images/compare_screen_placeholder_png.js
>> Unused images module: number-play/images/game_screen_placeholder_png.js
>> Unused images module: number-play/images/lab_screen_icon_png.js
>> Unused images module: number-play/images/lab_screen_placeholder_png.js
>> Unused images module: number-play/images/speaker_png.js
Fatal error: Perennial task failed:
AssertionError [ERR_ASSERTION]: Missing string information for vegas pattern.hour.minute.second
at /data/share/phet/continuous-testing/ct-snapshots/1636386236854/chipper/js/grunt/getStringMap.js:220:9
at Array.forEach (<anonymous>)
at /data/share/phet/continuous-testing/ct-snapshots/1636386236854/chipper/js/grunt/getStringMap.js:209:15
at Array.forEach (<anonymous>)
at /data/share/phet/continuous-testing/ct-snapshots/1636386236854/chipper/js/grunt/getStringMap.js:208:23
at Array.forEach (<anonymous>)
at module.exports (/data/share/phet/continuous-testing/ct-snapshots/1636386236854/chipper/js/grunt/getStringMap.js:153:24)
at module.exports (/data/share/phet/continuous-testing/ct-snapshots/1636386236854/chipper/js/grunt/buildRunnable.js:137:21)
at async /data/share/phet/continuous-testing/ct-snapshots/1636386236854/chipper/js/grunt/Gruntfile.js:280:11
at async wrap (/data/share/phet/continuous-testing/ct-snapshots/1636386236854/chipper/js/grunt/Gruntfile.js:56:7)
Full Error details:
AssertionError [ERR_ASSERTION]: Missing string information for vegas pattern.hour.minute.second
Snapshot from 11/8/2021, 8:43:56 AM

----------------------------------

number-play : pan-and-zoom-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1636386236854/number-play/number-play_en.html?continuousTest=%7B%22test%22%3A%5B%22number-play%22%2C%22pan-and-zoom-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1636386236854%22%2C%22timestamp%22%3A1636387424023%7D&brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=true
Query: brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=true
Uncaught TypeError: Cannot read properties of undefined (reading 'x')
TypeError: Cannot read properties of undefined (reading 'x')
at Vector2.distanceSquared (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1636386236854/chipper/dist/dot/js/Vector2.js:84:35)
at Vector2.distance (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1636386236854/chipper/dist/dot/js/Vector2.js:61:31)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1636386236854/chipper/dist/number-play/js/common/model/OnesPlayArea.js:209:54
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1636386236854/sherpa/lib/lodash-4.17.4.js:3738:18
at arrayMap (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1636386236854/sherpa/lib/lodash-4.17.4.js:660:23)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1636386236854/sherpa/lib/lodash-4.17.4.js:3737:24
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1636386236854/sherpa/lib/lodash-4.17.4.js:3554:27
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1636386236854/sherpa/lib/lodash-4.17.4.js:4920:15
at baseMap (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1636386236854/sherpa/lib/lodash-4.17.4.js:3553:7)
at baseOrderBy (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1636386236854/sherpa/lib/lodash-4.17.4.js:3736:20)
id: Bayes Chrome
Snapshot from 11/8/2021, 8:43:56 AM
```

**Comment by Luisav1** [comment] 2021-11-15 18:29
Thanks @KatieWoe, the vegas dependency was missing from Number Play, fixed in the commit above. Closing this issue.

**Comment by Luisav1** [comment] 2021-11-15 18:55
@KatieWoe Turns out the vegas dependency was not the issue and we're still working on it.

**Comment by pixelzoom** [comment] 2023-01-04 03:49
I did a brands=phet build, details below.  There are still a lot of "Unused string" warnings. But I could not reproduce the "Missing string information" error.  So I'm going to assume it's been fixed and close this issue.

<details>

```
% cd number-play
% grunt --brands=phet
Running "lint-all" task
[........................................] 100.00%

Running "report-media" task

Running "clean" task

Running "build" task
>> tsc complete: 22603ms
Building runnable repository (number-play, brands: phet)
Building brand: phet
>> Webpack build complete: 5346ms
>> Unused string: key=screen.lab, value=Lab
>> Unused string: key=zero, value=zero
>> Unused string: key=one, value=one
>> Unused string: key=two, value=two
>> Unused string: key=three, value=three
>> Unused string: key=four, value=four
>> Unused string: key=five, value=five
>> Unused string: key=six, value=six
>> Unused string: key=seven, value=seven
>> Unused string: key=eight, value=eight
>> Unused string: key=nine, value=nine
>> Unused string: key=ten, value=ten
>> Unused string: key=eleven, value=eleven
>> Unused string: key=twelve, value=twelve
>> Unused string: key=thirteen, value=thirteen
>> Unused string: key=fourteen, value=fourteen
>> Unused string: key=fifteen, value=fifteen
>> Unused string: key=sixteen, value=sixteen
>> Unused string: key=seventeen, value=seventeen
>> Unused string: key=eighteen, value=eighteen
>> Unused string: key=nineteen, value=nineteen
>> Unused string: key=twenty, value=twenty
>> Unused string: key=total, value=Total
>> Unused string: key=gameNameLevelNumberPattern, value={{gameName}}: Level {{levelNumber}}
>> Unused string: key=readAloudDescription, value=Hear the updated total as you interact.
>> Unused string: key=secondLanguage, value=Second Language
>> Unused string: key=secondLanguageDescription, value=Select a second language to support multilingual learning.
>> Unused string: key=showOnes, value=Show Ones
>> Unused string: key=showOnesDescription, value=Include the paper numbers on the Lab screen.
>> Unused string: key=noDeviceFoundDescription, value=There is no voice found on this device for the selected language(s).
>> Unused string: key=yourDeviceMaySupportDescription, value=Your device may support downloading an additional voice for your language.
>> Production minification complete: 21959ms (2670505 bytes)
>> Debug minification complete: 0ms (23391289 bytes)

Done.
% 
```

</details>

**Closed by pixelzoom** 2023-01-04 03:49 UTC
Labels: type:automated-testing
